before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

script:
  - ./build_keywords.sh
  - ./build_html.sh
  - git remote set-url "https://$username:$password@github.com/assafmo/nba-espn-stats-and-info.git"
  - git config user.name nba-espn-stats-and-info-bot
  - git add index.html keywords.list
  - git commit -m "`date -Iseconds`"
  - git push
