#sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

script:
  - ./build_keywords.sh
  - ./build_html.sh

#deploy:
#  - provider: pages
#  - skip_cleanup: true
#  - github_token: $GITHUB_TOKEN
#  - on:
#    - branch: master